name: feat
channels:
    - conda-forge
dependencies:
    - python
    - cmake>3.3
    - ninja
    - eigen
    - cython
    - pandas
    - scikit-learn
    - setuptools
    - shogun-cpp
    - wheel
    - pybind11
    - pip
    - pip:
        - eigency
        - pmlb
