name: feat
channels:
    - conda-forge
dependencies:
    - python
    - cmake
    - ninja
    - eigen
    - cython
    - pandas
    - scikit-learn
    - setuptools
    - shogun-cpp
    - wheel
    - pip
    - pip:
        - eigency
        - pmlb
