#!/bin/bash

check_for_python=true
choice="n"
njobs="4"
folder="build"

POSITIONAL=()
while [[ $# > 0 ]]
do
    key="$1"

    case $key in 
    -C)
        folder=$2
        shift
        shift
        ;;
    lpc)
        module load gcc/10.2.0
        shift
        ;;
    n)
        check_for_python=false
        shift
        ;;
    y)
        check_for_python=false
        choice="y"
        shift
        ;;
    -j|njobs)
        njobs="$2"
        shift
        shift
        ;;
    debug)
        folder="debug"
        shift
        ;;
    *) # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
   esac
done

echo "Build folder = ${folder}"
echo "Number of jobs = ${njobs}"

make -C ${folder} -j ${njobs}

if [ $check_for_python == true ] ; then
    read -p "Install python wrapper? (y/n) " choice
fi

if [ $choice == "y" ] ; then 
        echo "installing python module..."
        cd python
        rm -rf build 
        rm -rf dist
        python setup.py install
        cd ..
fi

echo "done"
