#!/bin/bash

if [ "$1" == "gpu" ] ; then
    make -C buildGPU -j8
elif [ "$1" == "debug" ] ; then
    make -C debug -j8
else
    make -C build -j8 
fi

if [ "$1" == "lpc" ] ; then
    module load gcc/5.2.0
    export EIGEN3_INCLUDE_DIR="$HOME/eigen-3.3.4/"
    export SHOGUN_DIR="$HOME/anaconda3/include/"
    export SHOGUN_LIB="$HOME/anaconda3/lib/"    
fi 

if [ $1 != "n" ] ; then  
    read -p "Install python wrapper? (y/n) " choice
    if [ $choice == "y" ] ; then 
        echo "installing python module..."
        cd python
        python setup.py install
        cd ..
    fi
fi
