#!/bin/bash

make -C build -j

check_for_python=true

if [ $# > 0 ] ; then 
    for var in $@ ; do
        if [ $var == "lpc" ] ; then
            module load gcc/5.2.0
            export EIGEN3_INCLUDE_DIR="$HOME/eigen-3.3.4/"
            export SHOGUN_DIR="$HOME/anaconda3/include/"
            export SHOGUN_LIB="$HOME/anaconda3/lib/"    
        elif [ $var == "y" ] || [ $var == "python" ] ; then
            echo "installing python module..."
            cd python
            rm -rf build 
            rm -rf dist
            python setup.py install
            cd ..
            check_for_python=false
        fi 
    done
fi

if [ $check_for_python == true ] ; then
    read -p "Install python wrapper? (y/n) " choice
    if [ $choice == "y" ] ; then 
        echo "installing python module..."
        cd python
        rm -rf build 
        rm -rf dist
        python setup.py install
        cd ..
    fi
fi
echo "done"
