# note: this should be used to update feat environment
name: feat-docs
channels:
    - conda-forge
dependencies:
    - sphinx
    - sphinx-material
    - recommonmark
    - nbsphinx
    - matplotlib
    - jupyter
    - seaborn
    - openssl
    - pip
    - pip:
        - sphinx-copybutton
