# note: this should be used to update feat-env only
name: feat-env
channels:
    - conda-forge
dependencies:
    - mkdocs=1.1
    - mkdocs-material
    - mkdocs-material-extensions=1.*
    - pymdown-extensions
    - pygments
