name: feat-env
channels:
    - conda-forge
dependencies:
    - python=3.*
    - cmake=3.18.*
    - eigen=3.3.*
    - cython=0.29.*
    - pandas=1.1.*
    - scikit-learn=0.23.*
    - setuptools=45.*
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    - pip=20.*
    - pip:
        - eigency==1.77
