name: install, test, docs
on: [push, pull_request]

env: 
  CACHE_NUMBER: 0

jobs:
  build_and_test_and_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 30
      - 
        name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
      - 
        name: Install
        run: | 
          micromamba env list
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          # python setup.py debug
          # pip install . -v
          python setup.py install
########################################
# tests
########################################
      - 
        name: Test Import
        run: |
          # which python
          cd ..
          # ls
          which python
          micromamba info
          python -c "from feat import Feat"
      - 
        name: Wrapper Test 
        run: |
          # which python
          cd tests
          # ls
          python wrappertest.py
      # - 
      #   name: Notebook Test
      #   run: |
      #     # which python
      #     cd tests
      #     # ls
      #     micromamba install jupyter
      #     python tests/nb_tests.py
########################################
# docs
########################################
      - 
        name: build docs
        run: |
          cd docs
          sudo apt-get install doxygen graphviz
          doxygen --version

          mkdir doxygen_site/
          doxygen Doxyfile

          micromamba info
          micromamba install pandoc
          pip install -r requirements.txt
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site