name: install and test
on:
  push:
    branches:
      - pip

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          # environment-file: environment.yml
          activate-environment: feat
          use-mamba: true
      - 
        name: Cache conda
        uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/feat
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml')}}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
        id: cache
      - 
        name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: | 
          mamba env update -n feat -f environment.yml 
      - 
        name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: | 
          python setup.py install
      - 
        name: Test Setup
        run: |
          cd tests
          ls
      - 
        name: Wrapper Test 
        run: |
          python wrappertest.py -v
      - 
        name: Notebook Test
        run: |
            python nb_tests.py
      - name: C++ Tests
        run: |

