name: install, test, docs
on:
  push:
    branches:
      - fix_op_type_install
  pull_request:
    branches:
      - fix_op_type_install


env: 
  CACHE_NUMBER: 0

jobs:
  build_and_test_and_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          # extra-specs: |
          #   python=3.7
          cache-env: true
          # cache-downloads: true
          # cache-downloads-key: ${{ runner.os }}-micromamba-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml'}}
      - 
        name: Install
        run: | 
          # python setup.py install
          pip install .
      - 
        name: Wrapper Test 
        run: |
          # which python
          cd tests
          # ls
          python wrappertest.py -v 1
      - 
        name: Notebook Test
        run: |
          # which python
          cd tests
          # ls
          micromamba install jupyter
          python nb_tests.py
########################################
# docs
########################################
      - 
        name: Install Doxygen
        run: sudo apt-get install doxygen
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: add docs environment
        run: |
          micromamba install -c conda-forge -y sphinx sphinx-material recommonmark seaborn nbsphinx
          micromamba install -c anaconda -y matplotlib jupyter 
          pip install sphinx-copybutton
          micromamba info
          micromamba list
      - 
        name: Check commands
        run: |
          doxygen --version
      - 
        name: doxygen docs
        run: |
          cd docs
          mkdir doxygen_site/
          doxygen Doxyfile
      - 
        name: sphinx docs
        run: |
          cd docs
          sphinx-build -b html ./ ../_site
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
