name: install, test, docs
on: [push, pull_request]

env: 
  CACHE_NUMBER: 0

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 30
      - 
        name: Install Feat environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
      - 
        name: Install
        run: | 
          micromamba env list
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          python setup.py install
########################################
# tests
########################################
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Test Import
        run: |
          cd ..
          which python
          micromamba info
          python -c "from feat import Feat"
      - 
        name: Wrapper Test 
        run: |
          # which python
          cd tests
          # ls
          python wrappertest.py -v 3
      # - 
      #   name: Notebook Test
      #   run: |
      #     # which python
      #     cd tests
      #     # ls
      #     micromamba install jupyter
      #     python tests/nb_tests.py
########################################
# docs
########################################
  docs:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: add docs environment dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
          extra-specs: |
            sphinx 
            sphinx-material 
            recommonmark 
            seaborn 
            nbsphinx 
            matplotlib 
            jupyter 
            sphinx-copybutton
      - 
        name: Install Doxygen
        run: sudo apt-get install doxygen
      - 
        name: Check commands
        run: |
          doxygen --version
      - 
        name: prep doxygen docs
        run: |
          cd docs
          mkdir doxygen_site/
          doxygen Doxyfile
      - 
        name: prep sphinx docs
        run: |
          micromamba info
          which python
          cd docs
          python -c "from feat import Feat"
          which sphinx-build
          sphinx-build -b html ./ ../_site
      - 
        name: make sphinx docs
        run: |
          cd docs
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site