name: install, test, docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


env: 
  CACHE_NUMBER: 0

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          # extra-specs: |
          #   python=3.7
          cache-env: true
          # cache-downloads: true
          # cache-downloads-key: ${{ runner.os }}-micromamba-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml'}}
      - 
        name: Install
        run: | 
          python setup.py install
      - 
        name: Wrapper Test 
        run: |
          # which python
          cd tests
          # ls
          python wrappertest.py -v 1
      - 
        name: Notebook Test
        run: |
          # which python
          cd tests
          # ls
          micromamba install jupyter
          python nb_tests.py
  build_docs:
    runs-on: ubuntu-latest
    needs: build_and_test
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Install Doxygen
        run: sudo apt-get install doxygen
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: add docs environment
        run: |
          # micromamba deactivate 
          # micromamba update -n feat -f ci/docs-environment.yml
          # micromamba activate feat
          micromamba install \ 
            sphinx \
            sphinx-material \
            recommonmark \
            nbsphinx
            matplotlib \
            jupyter \
            seaborn \ 
            -c conda-forge
          pip install sphinx-copybutton
          micromamba info
          micromamba list
      - 
        name: Check commands
        run: |
          micromamba list
          doxygen --version
      - 
        name: doxygen docs
        run: |
          cd docs
          mkdir doxygen_site/
          doxygen Doxyfile
      - 
        name: sphinx docs
        run: |
          cd docs
          sphinx-build -b html ./ ../_site
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../_site
