name: install and test
on:
  push:
    branches:
      - pip

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          extra-specs: |
            python=3.7
          cache-env: true
          cache-downloads: true
      - 
        name: Install
        run: | 
          python setup.py install
      - 
        name: Wrapper Test 
        run: |
          conda info
          cd tests
          ls
          which python
          conda run -n feat python wrappertest.py -v 1
      - 
        name: Wrapper Test 
        run: |
          python wrappertest.py -v
      - 
        name: Notebook Test
        run: |
          cd tests
          ls
          conda info
          conda run -n feat python nb_tests.py
