name: install, test, docs
on: [push, pull_request]

env: 
  CACHE_NUMBER: 0

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      # - 
      #   name: Load Feat environment with Micromamba
      #   uses: mamba-org/provision-with-micromamba@main
      #   with:
      #     environment-file: environment.yml
      #     cache-env: true
      - 
        name: add docs environment dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/ci-environment.yml
          cache-env: true
          cache-downloads: true
      - 
        name: Install
        run: | 
          micromamba env list
          export CMAKE_BUILD_PARALLEL_LEVEL=4
          python setup.py install
########################################
# tests
########################################
      - 
        name: Test Import
        run: |
          cd ..
          which python
          # micromamba info
          python -c "from feat import Feat"
      - 
        name: Wrapper Test 
        run: |
          # which python
          cd tests
          # ls
          python wrappertest.py -v 3
      # - 
      #   name: Notebook Test
      #   run: |
      #     # which python
      #     cd tests
      #     # ls
      #     micromamba install jupyter
      #     python tests/nb_tests.py
########################################
# docs
########################################
      - name: build docs
        run: |
          sudo apt-get install doxygen
          sudo apt-get install graphviz
          doxygen --version
          which python
          cd docs
          ls
          echo "sphinx-build -b html ./ ../_site"
          # sphinx-build -b html ./ ../_site
          micromamba info
          python -m sphinx.cmd.build -b html ./ ../_site
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site