name: install and test
on:
  push:
    branches:
      - pip

jobs:
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.run_job == 'true'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: feat
          use-mamba: true
      - 
        name: Install
        run: | 
          python setup.py install

      - name: Test
        run: |
          cd tests
          python wrapper_test.py -v
