name: build docs
on:
  push:
    branches:
      - master
    # paths:
    # - 'docs/**'
  pull_request:
    branches:
      - master
    # paths:
    # - 'docs/**'


env: 
  CACHE_NUMBER: 0

jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - 
        name: Install Doxygen
        run: sudo apt-get install doxygen
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
      - 
        name: add docs environment
        run: |
          micromamba deactivate 
          micromamba update -n feat -f ci/docs-environment.yml
          micromamba activate feat
          micromamba info
          micromamba list
      - 
        name: Check commands
        run: |
          micromamba list
          doxygen --version
      - 
        name: doxygen docs
        run: |
          cd docs
          mkdir doxygen_site/
          doxygen Doxyfile
      - 
        name: sphinx docs
        run: |
          micromamba list
          sphinx-build -b html . ../_site
          make html
      - 
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../_site
